name: inventpro
description: InventPro Flutter app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  assets:
    - lib/assets/icons/

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  http: ^1.1.0
  drift: ^2.11.0
  drift_flutter: ^0.2.8
  path_provider: ^2.0.17
  path: ^1.8.3
  mobile_scanner: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  drift_dev: ^2.11.0
